import type { LeaderboardEntry } from "@/types/leaderboard"

// Round 1 Mock Data
export const MOCK_ROUND_1_DATA: LeaderboardEntry[] = [
  {
    id: 1,
    rank: 1,
    fullName: "Chheang Sovanpanha",
    hackerRankId: "chheang.sovanpanha@student.cadt.edu.kh",
    group: "G1",
    scores: [10, 30, 50, 10, 10, 30],
    bonus: 5,
    totalPoints: 145,
  },
  {
    id: 2,
    rank: 2,
    fullName: "Sok Pisey",
    hackerRankId: "sok.pisey@student.cadt.edu.kh",
    group: "G2",
    scores: [10, 25, 45, 10, 8, 25],
    bonus: 3,
    totalPoints: 126,
  },
  {
    id: 3,
    rank: 3,
    fullName: "Lim Dara",
    hackerRankId: "lim.dara@student.cadt.edu.kh",
    group: "G1",
    scores: [8, 30, 40, 10, 10, 20],
    bonus: 2,
    totalPoints: 120,
  },
  {
    id: 4,
    rank: 4,
    fullName: "Chan Sophea",
    hackerRankId: "chan.sophea@student.cadt.edu.kh",
    group: "G3",
    scores: [10, 20, 50, 8, 10, 15],
    bonus: 1,
    totalPoints: 114,
  },
  {
    id: 5,
    rank: 5,
    fullName: "Pich Ratana",
    hackerRankId: "pich.ratana@student.cadt.edu.kh",
    group: "G2",
    scores: [8, 25, 35, 10, 8, 25],
    bonus: 1,
    totalPoints: 112,
  },
  {
    id: 6,
    rank: 6,
    fullName: "Meas Chenda",
    hackerRankId: "meas.chenda@student.cadt.edu.kh",
    group: "G1",
    scores: [10, 15, 40, 8, 10, 20],
    bonus: 0,
    totalPoints: 103,
  },
  {
    id: 7,
    rank: 7,
    fullName: "Keo Pisach",
    hackerRankId: "keo.pisach@student.cadt.edu.kh",
    group: "G3",
    scores: [6, 20, 35, 10, 8, 20],
    bonus: 0,
    totalPoints: 99,
  },
  {
    id: 8,
    rank: 8,
    fullName: "Noun Sreypov",
    hackerRankId: "noun.sreypov@student.cadt.edu.kh",
    group: "G2",
    scores: [8, 15, 30, 8, 10, 15],
    bonus: 0,
    totalPoints: 86,
  },
  {
    id: 9,
    rank: 9,
    fullName: "Heng Sopheak",
    hackerRankId: "heng.sopheak@student.cadt.edu.kh",
    group: "G3",
    scores: [5, 10, 25, 8, 8, 18],
    bonus: 0,
    totalPoints: 74,
  },
  {
    id: 10,
    rank: 10,
    fullName: "Ly Kimheng",
    hackerRankId: "ly.kimheng@student.cadt.edu.kh",
    group: "G1",
    scores: [6, 12, 20, 6, 10, 15],
    bonus: 0,
    totalPoints: 69,
  },
  // Additional participants for Round 1
  ...Array.from({ length: 40 }, (_, i) => ({
    id: i + 11,
    rank: i + 11,
    fullName: `Student Round1 ${i + 11}`,
    hackerRankId: `student.r1.${i + 11}@student.cadt.edu.kh`,
    group: ["G1", "G2", "G3"][i % 3] as "G1" | "G2" | "G3",
    scores: [
      Math.floor(Math.random() * 10) + 1,
      Math.floor(Math.random() * 20) + 5,
      Math.floor(Math.random() * 30) + 10,
      Math.floor(Math.random() * 10) + 1,
      Math.floor(Math.random() * 10) + 1,
      Math.floor(Math.random() * 20) + 5,
    ],
    bonus: Math.floor(Math.random() * 3),
    totalPoints: Math.floor(Math.random() * 50) + 30,
  })),
] as const

// Round 2 Mock Data - Different participants and scores
export const MOCK_ROUND_2_DATA: LeaderboardEntry[] = [
  {
    id: 1,
    rank: 1,
    fullName: "Lim Dara",
    hackerRankId: "lim.dara@student.cadt.edu.kh",
    group: "G1",
    scores: [15, 35, 45, 12, 15, 28],
    bonus: 4,
    totalPoints: 154,
  },
  {
    id: 2,
    rank: 2,
    fullName: "Chan Sophea",
    hackerRankId: "chan.sophea@student.cadt.edu.kh",
    group: "G3",
    scores: [12, 30, 50, 10, 12, 25],
    bonus: 3,
    totalPoints: 142,
  },
  {
    id: 3,
    rank: 3,
    fullName: "Chheang Sovanpanha",
    hackerRankId: "chheang.sovanpanha@student.cadt.edu.kh",
    group: "G1",
    scores: [10, 25, 40, 15, 10, 30],
    bonus: 2,
    totalPoints: 132,
  },
  {
    id: 4,
    rank: 4,
    fullName: "Pich Ratana",
    hackerRankId: "pich.ratana@student.cadt.edu.kh",
    group: "G2",
    scores: [12, 20, 45, 8, 12, 20],
    bonus: 2,
    totalPoints: 119,
  },
  {
    id: 5,
    rank: 5,
    fullName: "Sok Pisey",
    hackerRankId: "sok.pisey@student.cadt.edu.kh",
    group: "G2",
    scores: [8, 22, 35, 12, 10, 22],
    bonus: 1,
    totalPoints: 110,
  },
  {
    id: 6,
    rank: 6,
    fullName: "Keo Pisach",
    hackerRankId: "keo.pisach@student.cadt.edu.kh",
    group: "G3",
    scores: [10, 18, 30, 10, 12, 25],
    bonus: 1,
    totalPoints: 106,
  },
  {
    id: 7,
    rank: 7,
    fullName: "Meas Chenda",
    hackerRankId: "meas.chenda@student.cadt.edu.kh",
    group: "G1",
    scores: [8, 15, 35, 10, 8, 20],
    bonus: 0,
    totalPoints: 96,
  },
  {
    id: 8,
    rank: 8,
    fullName: "Heng Sopheak",
    hackerRankId: "heng.sopheak@student.cadt.edu.kh",
    group: "G3",
    scores: [6, 12, 30, 8, 10, 18],
    bonus: 1,
    totalPoints: 85,
  },
  {
    id: 9,
    rank: 9,
    fullName: "Noun Sreypov",
    hackerRankId: "noun.sreypov@student.cadt.edu.kh",
    group: "G2",
    scores: [8, 10, 25, 10, 8, 15],
    bonus: 0,
    totalPoints: 76,
  },
  {
    id: 10,
    rank: 10,
    fullName: "Ly Kimheng",
    hackerRankId: "ly.kimheng@student.cadt.edu.kh",
    group: "G1",
    scores: [5, 8, 22, 8, 10, 12],
    bonus: 0,
    totalPoints: 65,
  },
  // Additional participants for Round 2
  ...Array.from({ length: 40 }, (_, i) => ({
    id: i + 11,
    rank: i + 11,
    fullName: `Student Round2 ${i + 11}`,
    hackerRankId: `student.r2.${i + 11}@student.cadt.edu.kh`,
    group: ["G1", "G2", "G3"][i % 3] as "G1" | "G2" | "G3",
    scores: [
      Math.floor(Math.random() * 12) + 1,
      Math.floor(Math.random() * 25) + 5,
      Math.floor(Math.random() * 35) + 10,
      Math.floor(Math.random() * 12) + 1,
      Math.floor(Math.random() * 12) + 1,
      Math.floor(Math.random() * 25) + 5,
    ],
    bonus: Math.floor(Math.random() * 4),
    totalPoints: Math.floor(Math.random() * 60) + 25,
  })),
] as const

// Legacy mock data for backward compatibility
export const MOCK_LEADERBOARD_DATA: LeaderboardEntry[] = MOCK_ROUND_1_DATA
